// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");

const NODE_GLOBALS = {
  require: "readonly",
  module: "writable",
  process: "readonly",
  __dirname: "readonly",
  console: "readonly",
};

const JEST_GLOBALS = {
  jest: "readonly",
  describe: "readonly",
  it: "readonly",
  test: "readonly",
  expect: "readonly",
  beforeEach: "readonly",
  afterEach: "readonly",
  beforeAll: "readonly",
  afterAll: "readonly",
};

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      "dist/*",
      ".expo/*",
      ".diagram/*",
      "node_modules/*",
      // Generated by `expo prebuild` on the build server, never committed.
      "android/*",
      "ios/*",
    ],
  },
  {
    // Tests and the jest setup run under node with the jest globals injected.
    files: ["__tests__/**/*.{ts,tsx}", "jest.setup.jsx", "jest.config.js", "jest.global-setup.js"],
    languageOptions: { globals: { ...NODE_GLOBALS, ...JEST_GLOBALS } },
    rules: {
      // The setup file's icon mock is a factory, not a component worth naming.
      "react/display-name": "off",
    },
  },
  {
    // Dev tooling that node runs directly, not part of the app bundle.
    files: ["scripts/**/*.js"],
    languageOptions: { globals: NODE_GLOBALS },
  },
]);
